version: '3'
services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./assets:/app/assets
    depends_on:
      - postgres
      - redis
      - rabbitmq
  celery:
    build: .
    command: celery -A Reminder worker -l info -Q
    env_file:
      - .env
    entrypoint: ""
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
      - rabbitmq
  postgres:
    image: postgres:12.3
    restart: always
    env_file:
      - .env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    env_file:
      - .env
    volumes:
      - ./.data/redis:/data
  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.data/rabbitmq/log/:/var/log/rabbitmq
