version: "3"
services:
  db:
    image: postgres:12.3
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432   # external(not docker) and internal(docker) ports
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data